# Generated by Django 5.2.4 on 2025-11-04 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InwardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('date', models.DateField()),
                ('inward_slip_no', models.CharField(max_length=50)),
                ('yellow_white', models.CharField(max_length=20)),
                ('customer_dc_no', models.CharField(max_length=50)),
                ('wo_no', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('material_type', models.CharField(max_length=50)),
                ('thickness_mm', models.FloatField()),
                ('width_mm', models.FloatField()),
                ('length_mm', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('density', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prg_no', models.CharField(max_length=50)),
                ('prg_date', models.DateField()),
                ('planned_qty', models.IntegerField()),
                ('balance_qty', models.IntegerField()),
                ('used_weight_kg', models.FloatField()),
                ('components_per_sheet', models.IntegerField()),
                ('cut_length_per_sheet', models.FloatField()),
                ('pierce_per_sheet', models.FloatField()),
                ('planned_mins_per_sheet', models.FloatField()),
                ('inward_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='tracking.inwardentry')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_date', models.DateField()),
                ('shift', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('sheets_processed', models.IntegerField()),
                ('cycle_time_per_sheet', models.FloatField()),
                ('total_cycle_time', models.FloatField()),
                ('machine', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('program_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_logs', to='tracking.programdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('program_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tracking.programdetail')),
            ],
        ),
    ]
