# Generated by Django 5.2.4 on 2025-11-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwardentry',
            name='yellow_white',
            field=models.CharField(max_length=1),
        ),
    ]
